#!/usr/bin/with-contenv sh
#shellcheck shell=sh

sleep $((STATS_INTERVAL_MINUTES * 60))

PACKETS_SINCE_LAST_UPDATE=0
while read L; do
    NUM_PACKETS=$(echo $L | grep 'Packets sent in the last 30 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 2 | cut -d ',' -f 1 | tr -d ' ')
    TOTAL_PACKETS=$(echo $L | grep 'Packets sent in the last 30 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 3 | tr -d ' ')
    PACKETS_SINCE_LAST_UPDATE=$((PACKETS_SINCE_LAST_UPDATE + NUM_PACKETS))
done < $RBFEEDER_LOG_FILE

echo "Packets sent in past $STATS_INTERVAL_MINUTES minutes: $PACKETS_SINCE_LAST_UPDATE, total packets since container start: $TOTAL_PACKETS" |
    awk -W Interactive '{print "[stats] " $0}'

# truncate the log file
truncate --size=0 /var/log/rbfeeder.log
