#!/usr/bin/with-contenv bash
#shellcheck shell=bash

sleep $((STATS_INTERVAL_MINUTES * 60))

PACKETS_SINCE_LAST_UPDATE=0
while read -r L; do
    if echo "$L" | grep 'Packets sent in the last 30 seconds: ' > /dev/null 2>&1; then
        NUM_PACKETS=$(echo "$L" | grep 'Packets sent in the last 30 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 2 | cut -d ',' -f 1 | tr -d ' ')
        TOTAL_PACKETS=$(echo "$L" | grep 'Packets sent in the last 30 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 3 | tr -d ' ')
        PACKETS_SINCE_LAST_UPDATE=$((PACKETS_SINCE_LAST_UPDATE + NUM_PACKETS))
    fi
done < "$RBFEEDER_LOG_FILE"

echo "[stats] Packets sent in past $STATS_INTERVAL_MINUTES minutes: $PACKETS_SINCE_LAST_UPDATE, total packets since container start: $TOTAL_PACKETS"

# truncate the log file to 150 lines
echo "$(tail -150 "$RBFEEDER_LOG_FILE")" > "$RBFEEDER_LOG_FILE"
