#!/usr/bin/env bash
#shellcheck shell=bash disable=SC1091

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

# Show latest changelog
"${s6wrap[@]}" zcat /usr/share/doc/rbfeeder/changelog.gz | grep -B9999 -m 1 " --  "
