#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

set -eo pipefail

# Don't continue if UAT_RECEIVER_HOST isn't set
if [[ -z "$UAT_RECEIVER_HOST" ]]; then
    stop_service
else
    # shellcheck disable=SC2016
    exec "${s6wrap[@]}" socat -d -d TCP-LISTEN:30979,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30979}"
fi
