#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091,SC2207,SC2206

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

bad_servers=()

while true; do
    while read -r L; do
        if grep -q 'Could not start connection. Timeout.' <<< "$L"; then
            readarray -t current_bad <<< "$(netstat -tn | awk -F'[ :]*' '/33755/ {print $6}')"
            bad_servers+=(${current_bad[@]})
            readarray -t bad_servers <<< "$(printf "%s\n" "${bad_servers[@]}" | sort -u)"
            "${s6wrap[@]}" echo "[WARNING] rbfeeder connected to a bad server (current: ${current_bad[*]}; total bad list: ${bad_servers[*]}); restarting rbfeeder process"
            # this is cleaner than pkill because we don't know the exact command line (with or without qemu)
            kill "$(ps -ef |awk '/rbfeeder_arm/ && !/awk/ {print $2}')"
            echo > "$RBFEEDER_LOG_FILE"
        elif grep -q 'Connection with RadarBox24 server OK'  <<< "$L"; then
            "${s6wrap[@]}" echo "[INFO] rbfeeder connected to a good server! ($( netstat -tn | awk -F'[ :]*' '/33755/ && /ESTABLISHED/ {print $6}'))"
        fi
    done < "$RBFEEDER_LOG_FILE"
    sleep 5
done
