#!/command/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016

# Prevent writing of coredumps
#  - Reason for coredumps: https://github.com/mikenye/docker-radarbox/issues/9#issuecomment-633068833
#  - Changes to docker-compose.yml: https://github.com/mikenye/docker-radarbox/issues/10#issuecomment-634027861
ulimit -c 0

# can be run natively
if [ "$VERBOSE_LOGGING" == "true" ]; then
    /usr/bin/rbfeeder 2>&1 | \
        stdbuf -oL awk '{print "[rbfeeder] " $0}'
else
    /usr/bin/rbfeeder 2>&1 | \
        stdbuf -oL awk '! / Statistics updated every 60 seconds /' | \
        stdbuf -oL awk '! /Packets sent in the last 60 seconds: /' | \
        stdbuf -oL awk '! / Data sent: /' | \
        stdbuf -oL awk '! / Data received: /' | \
        stdbuf -oL awk '{print "[rbfeeder] " $0}'
fi
