#!/command/with-contenv bash
#shellcheck shell=bash disable=SC2016,SC1091,SC2154

source /scripts/common

# Prevent writing of coredumps
#  - Reason for coredumps: https://github.com/mikenye/docker-radarbox/issues/9#issuecomment-633068833
#  - Changes to docker-compose.yml: https://github.com/mikenye/docker-radarbox/issues/10#issuecomment-634027861
ulimit -c 0

if chk_enabled "$VERBOSE_LOGGING"; then
    exec "${s6wrap[@]}" /usr/bin/rbfeeder
elif chk_enabled "$QUIET_LOGS"; then
    exec "${s6wrap[@]}" /usr/bin/rbfeeder 2>/dev/stdout 1>/dev/null
else
    exec "${s6wrap[@]}" /usr/bin/rbfeeder > >(\
        stdbuf -oL grep -v -e "Statistics updated every 60 seconds" \
                           -e "Packets sent in the last 60 seconds:" \
                           -e "Data sent:" \
                           -e "Data received:" \
                           -e "messages with MLAT magic timestamp" \
        )
fi
