#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

sleep $((STATS_INTERVAL_MINUTES * 60))

PACKETS_SINCE_LAST_UPDATE=0
while read -r L; do
    if echo "$L" | grep 'Packets sent in the last 60 seconds: ' > /dev/null 2>&1; then
        NUM_PACKETS=$(echo "$L" | grep 'Packets sent in the last 60 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 2 | cut -d ',' -f 1 | tr -d ' ')
        TOTAL_PACKETS=$(echo "$L" | grep 'Packets sent in the last 60 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 3 | tr -d ' ')
        PACKETS_SINCE_LAST_UPDATE=$((PACKETS_SINCE_LAST_UPDATE + NUM_PACKETS))
    fi
done < "$RBFEEDER_LOG_FILE"

#shellcheck disable=SC2016
"${s6wrap[@]}" echo "Packets sent in past $STATS_INTERVAL_MINUTES minutes: $PACKETS_SINCE_LAST_UPDATE, total packets since container start: $TOTAL_PACKETS"

# truncate the log file to 150 lines
#shellcheck disable=SC2005
echo "$(tail -150 "$RBFEEDER_LOG_FILE")" > "$RBFEEDER_LOG_FILE"
