#!/command/with-contenv bash
#shellcheck shell=bash disable=SC1091

source /scripts/common
s6wrap=(s6wrap --quiet --timestamps --prepend="$(basename "$0")" --args)

if chk_enabled "$QUIET_LOGS"; then
    # stats won't work if QUIET_LOGS is enabled
    stop_service
fi

PACKET_LINES="$(grep -e 'Packets sent in the last 60 seconds: ' "$RBFEEDER_LOG_FILE" | tail -n ${STATS_INTERVAL_MINUTES})"

if [[ -n "$PACKET_LINES" ]]; then

    PACKETS_SINCE_LAST_UPDATE=0
    while read -r L; do
        NUM_PACKETS=$(echo "$L" | grep 'Packets sent in the last 60 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 2 | cut -d ',' -f 1 | tr -d ' ')
        TOTAL_PACKETS=$(echo "$L" | grep 'Packets sent in the last 60 seconds: ' | cut -d ']' -f 2 | cut -d ':' -f 3 | tr -d ' ')
        PACKETS_SINCE_LAST_UPDATE=$((PACKETS_SINCE_LAST_UPDATE + NUM_PACKETS))
    done <<< "${PACKET_LINES}"

    #shellcheck disable=SC2016
    "${s6wrap[@]}" echo "Packets sent in past $STATS_INTERVAL_MINUTES minutes: $PACKETS_SINCE_LAST_UPDATE, total packets since rbfeeder start: $TOTAL_PACKETS"
fi

# truncate the log file to 150 lines
#shellcheck disable=SC2005
echo "$(tail -150 "$RBFEEDER_LOG_FILE")" > "$RBFEEDER_LOG_FILE"

exec sleep $((STATS_INTERVAL_MINUTES * 60))
