#!/usr/bin/with-contenv bash
#shellcheck shell=bash
#shellcheck disable=SC2016

sleep 30

if tail -20 /var/log/rbfeeder.log | grep "CPU Serial empty" > /dev/null 2>&1; then
    echo ""
    echo "************ ATTENTION! ************"
    echo ""
    echo "In order to fix the 'CPU Serial empty' issue you are experiencing,"
    echo "please see: https://github.com/mikenye/docker-radarbox/blob/master/README.md#workaround-for-cpu-serial"
    echo ""
    echo "************************************"
    echo ""
fi

sleep 30
