#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -eo pipefail

# Don't continue if UAT_RECEIVER_HOST isn't set
if [[ -z "$UAT_RECEIVER_HOST" ]]; then
  sleep 86400
  exit 0
fi

# shellcheck disable=SC2016
socat -d -d TCP-LISTEN:30979,fork TCP:"$UAT_RECEIVER_HOST":"${UAT_RECEIVER_PORT:-30978}" \
 2>&1 | awk -W Interactive '{print "[978json-splitter] " $0}'

sleep 5
