#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# try to get station serial number
SN=$(grep -E "^sn=.*$" /etc/rbfeeder.ini)
MLAT_USER=$(echo "$SN" | cut -d "=" -f 2 | tr -d " ")

if [[ -z "$MLAT_USER" ]]; then
  echo "[mlat-client] Delaying mlat-client startup until rbfeeder receives station sn..."
  sleep 30
  exit 1
fi

exec /usr/local/bin/mlat-client \
    --input-type "${MLAT_INPUT_TYPE}" \
    --input-connect "${BEASTHOST}:${BEASTPORT}" \
    --results beast,listen,30105 \
    --results beast,connect,127.0.0.1:30104 \
    --lat "${LAT}" \
    --lon "${LONG}" \
    --alt "${ALT}m" \
    --user "${MLAT_USER}" \
    --server "${MLAT_SERVER}" \
    2>&1 | awk -W Interactive '{print "[mlat-client] " $0}'
