#!/usr/bin/with-contenv sh
#shellcheck shell=sh

# try to get station serial number
SN=$(grep -E "^sn=.*$" /etc/rbfeeder.ini)

if grep -E "^sn=.*$" /etc/rbfeeder.ini; then
    echo "[mlat-client] Delaying mlat-client startup until rbfeeder receives station sn..."
    sleep 30
    
else
    
    MLAT_USER=$(echo "$SN" | cut -d "=" -f 2)

    if [ "$(uname -m)" = "x86_64" ]
    then
        
        exec /usr/bin/qemu-arm-static /usr/bin/python3 /usr/bin/mlat-client \
            --input-type "${MLAT_INPUT_TYPE}" \
            --input-connect "${BEASTHOST}:${BEASTPORT}" \
            --results beast,listen,30105 \
            --lat "${LAT}" \
            --lon "${LONG}" \
            --alt "${ALT}m" \
            --user "${MLAT_USER}" \
            --server "${MLAT_SERVER}" \
            2>&1 | awk -W Interactive '{print "[mlat-client] " $0}'

    elif [ "$(uname -m)" = "armv7l" ]
    then
        exec /usr/bin/mlat-client \
            --input-type "${MLAT_INPUT_TYPE}" \
            --input-connect "${BEASTHOST}:${BEASTPORT}" \
            --results beast,listen,30105 \
            --lat "${LAT}" \
            --lon "${LONG}" \
            --alt "${ALT}m" \
            --user "${MLAT_USER}" \
            --server "${MLAT_SERVER}" \
            2>&1 | awk -W Interactive '{print "[mlat-client] " $0}'

    elif [ "$(uname -m)" = "armhf" ]
    then
        exec /usr/bin/mlat-client \
            --input-type "${MLAT_INPUT_TYPE}" \
            --input-connect "${BEASTHOST}:${BEASTPORT}" \
            --results beast,listen,30105 \
            --lat "${LAT}" \
            --lon "${LONG}" \
            --alt "${ALT}m" \
            --user "${MLAT_USER}" \
            --server "${MLAT_SERVER}" \
            2>&1 | awk -W Interactive '{print "[mlat-client] " $0}'

    elif [ "$(uname -m)" = "aarch64" ]
    then
        exec /usr/bin/mlat-client \
            --input-type "${MLAT_INPUT_TYPE}" \
            --input-connect "${BEASTHOST}:${BEASTPORT}" \
            --results beast,listen,30105 \
            --lat "${LAT}" \
            --lon "${LONG}" \
            --alt "${ALT}m" \
            --user "${MLAT_USER}" \
            --server "${MLAT_SERVER}" \
            2>&1 | awk -W Interactive '{print "[mlat-client] " $0}'

    else
        sleep 60
        exit 1
    fi

fi
