#!/usr/bin/with-contenv bash
#shellcheck shell=bash

# Prevent writing of coredumps
#  - Reason for coredumps: https://github.com/mikenye/docker-radarbox/issues/9#issuecomment-633068833
#  - Changes to docker-compose.yml: https://github.com/mikenye/docker-radarbox/issues/10#issuecomment-634027861
ulimit -c 0

if [ "$(uname -m)" = "x86_64" ]
then
    if [ "$VERBOSE_LOGGING" == "true" ]; then
        /usr/bin/qemu-arm-static /usr/bin/rbfeeder 2>&1 | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    else
        /usr/bin/rbfeeder 2>&1 | \
            awk '! / Statistics updated every 30 seconds /' | \
            awk '! /Packets sent in the last 30 seconds: /' | \
            awk '! / Data sent: /' | \
            awk '! / Data received: /' | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi

elif [ "$(uname -m)" = "armv7l" ]
then
    if [ "$VERBOSE_LOGGING" == "true" ]; then
        /usr/bin/rbfeeder 2>&1 | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    else
        /usr/bin/rbfeeder 2>&1 | \
            awk '! / Statistics updated every 30 seconds /' | \
            awk '! /Packets sent in the last 30 seconds: /' | \
            awk '! / Data sent: /' | \
            awk '! / Data received: /' | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi

elif [ "$(uname -m)" = "armhf" ]
then
    if [ "$VERBOSE_LOGGING" == "true" ]; then
        /usr/bin/rbfeeder 2>&1 | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    else
        /usr/bin/rbfeeder 2>&1 | \
            awk '! / Statistics updated every 30 seconds /' | \
            awk '! /Packets sent in the last 30 seconds: /' | \
            awk '! / Data sent: /' | \
            awk '! / Data received: /' | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi

elif [ "$(uname -m)" = "aarch64" ]
then
    if [ "$VERBOSE_LOGGING" == "true" ]; then
        /usr/bin/rbfeeder 2>&1 | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    else
        /usr/bin/rbfeeder 2>&1 | \
            awk '! / Statistics updated every 30 seconds /' | \
            awk '! /Packets sent in the last 30 seconds: /' | \
            awk '! / Data sent: /' | \
            awk '! / Data received: /' | \
            stdbuf -o0 awk '{print "[rbfeeder] " strftime("%Y/%m/%d %H:%M:%S", systime()) " " $0}'
    fi
else
    echo ""
    echo "ERROR!"
    echo "This build is running on an unsupported architecture ($(uname -m))."
    echo "Please raise an issue on this container's GitHub reporting this."
    echo ""
    # Container failed to start up, sleep forever
    sleep 86400
    exit 1
fi